### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by adlrocha** [filecoin-project/index-provider#12]
The goal of this issue is to track the list of unit tests that are flaky and need some extra care to make it work:
_If you see any other flaky test that needs to be investigated please add it to the list_
- [ ] `TestNotifyPublish` from `engine_test.go` (fails in MacOS go 1.17)
     - This one is probably due to the use of `time.Sleep` instead of an async approach for tests. It fails in `go test -race` with runs slower than vanilla `go test`

**Comment by masih** [comment]
Also this:
https://github.com/filecoin-project/indexer-reference-provider/pull/22/checks?check_run_id=3554562406

**Comment by masih** [comment]
https://github.com/filecoin-project/indexer-reference-provider/pull/28/commits/f92facb762fe04b4cf09bc03103a98c994a362c0

**Comment by adlrocha** [comment]
Quick note: once we figure out how to fix these flaky tests we should propagate the changes to https://github.com/willscott/go-legs and https://github.com/filecoin-project/storetheindex/blob/main/internal/ingest/ingest_test.go which are also using similar sync tests (and sleeps) for the pubsub interaction.

**Comment by masih** [comment]
`TestNotifyPublish` is also flaky https://github.com/filecoin-project/indexer-reference-provider/runs/3580876467?check_suite_focus=true

**Comment by mvdan** [comment]
The fix is now in go-libp2p-pubsub, and about to be merged into go-legs; there's just one test that's hanging for some reason: https://github.com/filecoin-project/go-legs/pull/26

When that's merged, then we'll need to bump go-legs in the indexer repos, e.g. https://github.com/filecoin-project/index-provider/pull/81.

**Comment by masih** [comment]
Fixed by https://github.com/filecoin-project/index-provider/pull/193
