### ISSUE TITLE
Removal advertisements are not syncable 

### ISSUE THREAD

**Issue by masih** [filecoin-project/index-provider#174]
Syncing removal advertisements fails because the link system [tries to look up an internal mapping ](https://github.com/filecoin-project/index-provider/blob/main/engine/linksystem.go#L78)of advertisement context ID which is [removed](https://github.com/filecoin-project/index-provider/blob/main/engine/engine.go#L439) as part of publishing the removal advertisement.

This makes all syncs for such advertisements fail.

Consider checking if the advertisement is a removal ad and do not attempt to look up entries for it from callback, since they may no longer be there. 

For "remove all" advertisements, the check is straight forward: check if entries link is `NoEntries` and if so do not attempt to look up entries. 
For removal advertisements with explicit list of multihashes rework in engine is needed to store that list permanently, since engine must be able to serve the advertisements it publishes.

**Comment by gammazero** [comment]
Do we even want to support removal other than removeall?  Supporting it will also require a way to specify _which_ multihashes to remove.

**Comment by masih** [comment]
My understanding was that if ad is a removal ad and entries link points to something other than `NoEntires` constant then only those multihashes get removed?

Is that no longer valid?

**Comment by willscott** [comment]
I'd like to keep this as simple as possible. can we only have support for 'remove the entire contextID'? for any partial removal w/i a context ID you then still need to get all previous entries for the context id to know which subset is removed so it's quite inefficient. I'd prefer not to support any more code paths than absolutely necessary here.
