### ISSUE TITLE
Upgrade index-provider in lotus

### ISSUE THREAD

**Issue by masih** [filecoin-project/index-provider#238]
Trickle dependencies up stream and upgrade index-provider in lotus.
This needs an upgrade to go-fil-market first then lotus.

**Comment by jennijuju** [comment]
@hannahhoward @dirkmc how do you feel about the above dep update in gdt?

fyi - in lotus we have already bumped to 	`github.com/libp2p/go-libp2p v0.19.4, github.com/libp2p/go-libp2p-core v0.15.1` so we already have that breaking change.

**Comment by hannahhoward** [comment]
Hey @jennijuju we have bumped already for go-data-transfer v2, but can backport to v1 -- is this for v17.1 release? We are targeting v17.2 for go-data-transfer v2.

**Comment by jennijuju** [comment]
@hannahhoward this is for v1.17.0 (current train) actually - as indexer provider is "broken" in lotus market atm.

**Comment by hannahhoward** [comment]
oh sorry... I mean 0.17.0 for backport, 0.17.1 for v2

**Comment by hannahhoward** [comment]
https://github.com/filecoin-project/go-data-transfer/pull/341

**Comment by jennijuju** [comment]
https://github.com/filecoin-project/go-data-transfer/releases/tag/v1.15.2

**Comment by masih** [comment]
@jennijuju Update on this: go-fil-markets upgraded and released. Upgrade in Lotus, however will require a range of upgrades across dependencies due to breaking changes in go-cid `0.2.0`. Off the top of my head the dependencies include: 
* ffi
* go-car/v2
* go-ipfs-http-client
