### ISSUE TITLE
Add option to announce ads to an explicit indexer

### ISSUE THREAD

**Issue by masih** [filecoin-project/index-provider#250]
Add an option that allows the provider engine to announce ads to an explicit indexer

**Comment by gammazero** [comment]
If the provider is bootstrapped to the target indexer, then ads will be announced over pubsub to the indexer and will not need to be whitelisted by the mainnet nodes.

There is also the `announce-http` command:
```
announce-http      Publish an announcement message for the latest advertisement to a specific indexer via http
```
This can be executed manually or can be executed by a cron job.

@masih What additional functionality is this issue asking for?

**Comment by masih** [comment]
Yep except we want programatic engine API option for it.
