### ISSUE TITLE
Handle `remove` Advertisements in LinkSystem when list of entries aren't available

### ISSUE THREAD

**Issue by adlrocha** [filecoin-project/index-provider#38]
A provider may not have the list of multihashes available when receiving a request for ingestion of a remove advertisement. In this case, instead of generating the linked list of entries that need to be removed, the linksystem should check if it is a remove advertisement, and not follow the link for the list of entries (as they won't be available and it would make the exchange fail)
https://github.com/filecoin-project/indexer-reference-provider/blob/78768e2546a7f81fe7c6237644f5598a83ea5258/core/engine/linksystem.go#L100

For advertismeents with `isRm == true` we should avoid trigerring the callback and traversing the `Entries` link: https://github.com/filecoin-project/indexer-reference-provider/blob/78768e2546a7f81fe7c6237644f5598a83ea5258/core/engine/linksystem.go#L109

This issue is related with https://github.com/filecoin-project/storetheindex/issues/78

**Comment by masih** [comment]
Fixed as part of: https://github.com/filecoin-project/index-provider/issues/174
