### ISSUE TITLE
tracking of new cars

### ISSUE THREAD

**Issue by willscott** [filecoin-project/index-provider#4]
Currently the mvp runs as a daemon.

we should add a code interface path for noticing a new CAR file
we should then implement one or both of 
* [x] P1: client command pointing to a car `reference-provider add my.carv2`
* [ ] P2: filesystem inotify watcher that notices a new car added to a folder

**Comment by masih** [comment]
When added explicitly via an `add` command we could ask the user to supply `metadata` via CLI.

@willscott In a case where CAR files are detected by watching a directory, what are your thoughts on what the `metadata` should be?

**Comment by willscott** [comment]
i don't think we need to expose this. The metadata should be some identifier of the car, that the client can use in establishing a retrieval session back to the provider to identify the car file when it attempts retrieval of a CID in the car.

We get to design the identifier/metadata that the reference provider uses for this round-trip

**Comment by masih** [comment]
@willscott do we still need the filesystem watcher?

**Comment by willscott** [comment]
nope. i think okay to skip this for now unless we start getting requests for it
