### ISSUE TITLE
Authenticate requests for advertisements

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/index-provider#46]
- depends on https://github.com/filecoin-project/go-legs/issues/20
- strategy TBD
- should probably be locked tight (don't accept anything that's not a known advertisement CID, possibly validate indexer address)

**Comment by willscott** [comment]
> don't accept anything that's not a known advertisement CID
this shouldn't be a big issue as long as we have a separate data store / namespace used for a legs instance. then there's nothing else that exists that can be requested, right?
> possibly validate indexer address
if we're an open system allowing new indexers to show up i don't think we can do this.

so i'm not sure there's much meaningful we can do here

**Comment by masih** [comment]
@hannahhoward  please feel free to reopen if you think this is still needed.
